<option value="Ujanpara">Ujanpara</option>
<option value="North West">North West</option>
<option value="South West">South West</option>
<option value="Debitola">Debitola</option>
<option value="Kazigaon">Kazigaon</option>
<option value="Modati">Modati</option>
<option value="Monglajhora">Monglajhora</option>
<option value="Polashguri-Debitola">Polashguri-Debitola</option>
<option value="Tipkai">Tipkai</option>
<option value="Aflagaon">Aflagaon</option>
<option value="Binnachara">Binnachara</option>
<option value="Bongshigaon">Bongshigaon</option>
<option value="Bonorgaon">Bonorgaon</option>
<option value="Boragari">Boragari</option>
<option value="Borshijhora">Borshijhora</option>
<option value="Chithila">Chithila</option>
<option value="Dhauliguri-Dotma">Dhauliguri-Dotma</option>
<option value="Dumuriguri">Dumuriguri</option>
<option value="Gossainichima">Gossainichima</option>
<option value="Habrubari">Habrubari</option>
<option value="Hokmabil">Hokmabil</option>
<option value="Jagdai">Jagdai</option>
<option value="Jharbari">Jharbari</option>
<option value="Koraitari">Koraitari</option>
<option value="Mahendrapur/Saralpara">Mahendrapur/Saralpara</option>
<option value="Nepalpara">Nepalpara</option>
<option value="Onthaibil">Onthaibil</option>
<option value="Pochagarh">Pochagarh</option>
<option value="Pratapkhata">Pratapkhata</option>
<option value="Ramfalbil">Ramfalbil</option>
<option value="Serfanguri">Serfanguri</option>
<option value="Shaktiashram">Shaktiashram</option>
<option value="Sialmari">Sialmari</option>
<option value="Murshuljhora">Murshuljhora</option>
<option value="Babubil">Babubil</option>
<option value="Bhoraguri">Bhoraguri</option>
<option value="Bhumka">Bhumka</option>
<option value="Dhoulaguri/Gossaigaon">Dhoulaguri/Gossaigaon</option>
<option value="Habrubari">Habrubari</option>
<option value="Harbhanga/Gossaigaon">Harbhanga/Gossaigaon</option>
<option value="Joypur">Joypur</option>
<option value="Kartimari">Kartimari</option>
<option value="Kartimari/Asharkandi">Kartimari/Asharkandi</option>
<option value="Milon Bazar">Milon Bazar</option>
<option value="Padmabil">Padmabil</option>
<option value="Panbari">Panbari</option>
<option value="Rimijhimi">Rimijhimi</option>
<option value="Satyapur">Satyapur</option>
<option value="Tulsibil">Tulsibil</option>
<option value="Bhairaguri">Bhairaguri</option>
<option value="Failaguri">Failaguri</option>
<option value="Grahampur">Grahampur</option>
<option value="Haraputa">Haraputa</option>
<option value="Majadabri">Majadabri</option>
<option value="Rangsupur">Rangsupur</option>
<option value="Srirampur">Srirampur</option>
<option value="Thakurpur">Thakurpur</option>
<option value="Anthaibari (Amritpur)">Anthaibari (Amritpur)</option>
<option value="Bairali">Bairali</option>
<option value="Balagaon">Balagaon</option>
<option value="Ballimari">Ballimari</option>
<option value="Barzabil">Barzabil</option>
<option value="Bhomrabil">Bhomrabil</option>
<option value="Bhorpur">Bhorpur</option>
<option value="Binnyakhata">Binnyakhata</option>
<option value="Borobhadha">Borobhadha</option>
<option value="Boshgaon">Boshgaon</option>
<option value="Burachara">Burachara</option>
<option value="Gardenpur">Gardenpur</option>
<option value="Gongia">Gongia</option>
<option value="Guwabari">Guwabari</option>
<option value="Hatigarh">Hatigarh</option>
<option value="Hawriapet">Hawriapet</option>
<option value="Hudumkata">Hudumkata</option>
<option value="Janaligaon">Janaligaon</option>
<option value="Jaraguri-Goladangi">Jaraguri-Goladangi</option>
<option value="Joleswari">Joleswari</option>
<option value="Kachugaon">Kachugaon</option>
<option value="Kamalsing">Kamalsing</option>
<option value="Kashibari">Kashibari</option>
<option value="Maktaigaon">Maktaigaon</option>
<option value="Malaguri">Malaguri</option>
<option value="Mojati">Mojati</option>
<option value="Polashguri">Polashguri</option>
<option value="Raikhunbari">Raikhunbari</option>
<option value="Raimona">Raimona</option>
<option value="Sapkata">Sapkata</option>
<option value="Simultapu">Simultapu</option>
<option value="Takampur">Takampur</option>
<option value="Amguri">Amguri</option>
<option value="Baruapara">Baruapara</option>
<option value="Bhadranpur/Basbari">Bhadranpur/Basbari</option>
<option value="Bhatiapara">Bhatiapara</option>
<option value="Bhotgaon">Bhotgaon</option>
<option value="Bishmuri">Bishmuri</option>
<option value="Daloagaon">Daloagaon</option>
<option value="Deborgaon">Deborgaon</option>
<option value="Dholmara">Dholmara</option>
<option value="East Maligaon/Mohanpur">East Maligaon/Mohanpur</option>
<option value="Fulguri">Fulguri</option>
<option value="Haloadol">Haloadol</option>
<option value="Haltugaon">Haltugaon</option>
<option value="Harinaguri">Harinaguri</option>
<option value="Kalipukhuri">Kalipukhuri</option>
<option value="Kalugaon/Subaijhar">Kalugaon/Subaijhar</option>
<option value="Karigaon Tarang Serfang">Karigaon Tarang Serfang</option>
<option value="Kurshakati-Kokrajhar">Kurshakati-Kokrajhar</option>
<option value="Magurmari">Magurmari</option>
<option value="Maoriagaon">Maoriagaon</option>
<option value="Nadangari">Nadangari</option>
<option value="No. 2 Gendrabil">No. 2 Gendrabil</option>
<option value="North Nayekgaon">North Nayekgaon</option>
<option value="Owabari">Owabari</option>
<option value="Pachim Maligaon">Pachim Maligaon</option>
<option value="Patgaon">Patgaon</option>
<option value="Salakati">Salakati</option>
<option value="Sijuguri">Sijuguri</option>
<option value="Simborgaon">Simborgaon</option>
<option value="South Nayekgaon">South Nayekgaon</option>
<option value="Sukanjhora">Sukanjhora</option>
<option value="Tilokgaon">Tilokgaon</option>
<option value="Tinali">Tinali</option>
<option value="Titaguri">Titaguri</option>
<option value="Ultapani - Labanyapur">Ultapani - Labanyapur</option>
<option value="Jalabila">Jalabila</option>
<option value="Mohamaya">Mohamaya</option>
<option value="Bashbari">Bashbari</option>
<option value="Joldoba">Joldoba</option>
<option value="Kurshakati - Rupshi">Kurshakati - Rupshi</option>
<option value="Rupshi">Rupshi</option>
<option value="Ananda-Betini">Ananda-Betini</option>
<option value="Ashrabari">Ashrabari</option>
<option value="Bamungaon-Dattapur">Bamungaon-Dattapur</option>
<option value="Bangaldoba">Bangaldoba</option>
<option value="Bengtol">Bengtol</option>
<option value="Bengtol-Serfang">Bengtol-Serfang</option>
<option value="Besorbari-Nangalbanga">Besorbari-Nangalbanga</option>
<option value="Birhangaon">Birhangaon</option>
<option value="Chapaguri">Chapaguri</option>
<option value="Dangtol">Dangtol</option>
<option value="Deosri">Deosri</option>
<option value="Fulguri">Fulguri</option>
<option value="Garubhasa">Garubhasa</option>
<option value="Hatisar">Hatisar</option>
<option value="Kajalgaon">Kajalgaon</option>
<option value="Kashikotra">Kashikotra</option>
<option value="Khungring">Khungring</option>
<option value="Kodamtola">Kodamtola</option>
<option value="Malivita">Malivita</option>
<option value="Ouguri">Ouguri</option>
<option value="Paddapur">Paddapur</option>
<option value="Patabari">Patabari</option>
<option value="Ranchaidham">Ranchaidham</option>
<option value="Runikhata">Runikhata</option>
<option value="Santipur">Santipur</option>
<option value="Shyamthaibari">Shyamthaibari</option>
<option value="Sidli">Sidli</option>
<option value="Subaijhar">Subaijhar</option>
<option value="Thaikajhora">Thaikajhora</option>
<option value="Tilokgaon">Tilokgaon</option>
<option value="Tukrajhar">Tukrajhar</option>
<option value="Alaori">Alaori</option>
<option value="Amguri">Amguri</option>
<option value="Amteka">Amteka</option>
<option value="Bagargaon">Bagargaon</option>
<option value="Ballamguri">Ballamguri</option>
<option value="Barlawgaon">Barlawgaon</option>
<option value="Barpathar">Barpathar</option>
<option value="Bhabanipur">Bhabanipur</option>
<option value="Bhangnamari">Bhangnamari</option>
<option value="Bishnupur">Bishnupur</option>
<option value="Deosri">Deosri</option>
<option value="Fulguri">Fulguri</option>
<option value="Garubhasa">Garubhasa</option>
<option value="Hatisar">Hatisar</option>
<option value="Kajalgaon">Kajalgaon</option>
<option value="Kashikotra">Kashikotra</option>
<option value="Khungring">Khungring</option>
<option value="Kodamtola">Kodamtola</option>
<option value="Malivita">Malivita</option>
<option value="Ouguri">Ouguri</option>
<option value="Paddapur">Paddapur</option>
<option value="Patabari">Patabari</option>
<option value="Ranchaidham">Ranchaidham</option>
<option value="Runikhata">Runikhata</option>
<option value="Santipur">Santipur</option>
<option value="Shyamthaibari">Shyamthaibari</option>
<option value="Sidli">Sidli</option>
<option value="Subaijhar">Subaijhar</option>
<option value="Thaikajhora">Thaikajhora</option>
<option value="Tilokgaon">Tilokgaon</option>
<option value="Tukrajhar">Tukrajhar</option>
<option value="Alukhunda">Alukhunda</option>
<option value="Bhangnamari">Bhangnamari</option>
<option value="Bijni Gaon">Bijni Gaon</option>
<option value="Chatianguri">Chatianguri</option>
<option value="Dangaigaon">Dangaigaon</option>
<option value="Dewanpara">Dewanpara</option>
<option value="Gargaon Bhalatal">Gargaon Bhalatal</option>
<option value="Malipara">Malipara</option>
<option value="Monakocha">Monakocha</option>
<option value="Mongolian">Mongolian</option>
<option value="Pashlabari Gargaon">Pashlabari Gargaon</option>
<option value="Barama">Barama</option>
<option value="Debachara">Debachara</option>
<option value="Kaklabari">Kaklabari</option>
<option value="Kharuajan">Kharuajan</option>
<option value="Merkuchi">Merkuchi</option>
<option value="Puransripur">Puransripur</option>
<option value="Adalbari">Adalbari</option>
<option value="Ambari (Mushalpur)">Ambari (Mushalpur)</option>
<option value="Athiabari">Athiabari</option>
<option value="Banganabari">Banganabari</option>
<option value="Bathouguri">Bathouguri</option>
<option value="Bhogpara">Bhogpara</option>
<option value="Borbari">Borbari</option>
<option value="Doomni">Doomni</option>
<option value="Madhupur">Madhupur</option>
<option value="Narayanpur">Narayanpur</option>
<option value="Nikashi">Nikashi</option>
<option value="Thamna">Thamna</option>
<option value="Adla">Adla</option>
<option value="Angardhowa">Angardhowa</option>
<option value="Baganpara">Baganpara</option>
<option value="Bagulamari">Bagulamari</option>
<option value="Gerua">Gerua</option>
<option value="Ghoramara">Ghoramara</option>
<option value="Jopadong">Jopadong</option>
<option value="Pakhamara">Pakhamara</option>
<option value="Subankhata">Subankhata</option>
<option value="Bahbari">Bahbari</option>
<option value="Barapeta">Barapeta</option>
<option value="Bonmaja">Bonmaja</option>
<option value="Chunbari">Chunbari</option>
<option value="Dakhin Howly">Dakhin Howly</option>
<option value="Dhekiajani">Dhekiajani</option>
<option value="Gobardhana">Gobardhana</option>
<option value="Khusrabari">Khusrabari</option>
<option value="Mainamata Pathar">Mainamata Pathar</option>
<option value="Mairajhar Pathar">Mairajhar Pathar</option>
<option value="Nimua">Nimua</option>
<option value="Paschim Howly">Paschim Howly</option>
<option value="Pub Howly">Pub Howly</option>
<option value="Uttar Howly">Uttar Howly</option>
<option value="Uttar Kharija Bijni">Uttar Kharija Bijni</option>
<option value="Baghdoba">Baghdoba</option>
<option value="Balabari">Balabari</option>
<option value="Barghuli">Barghuli</option>
<option value="Betna">Betna</option>
<option value="Deosunga">Deosunga</option>
<option value="Deulkuchi">Deulkuchi</option>
<option value="Dhepargaon">Dhepargaon</option>
<option value="Gopchar">Gopchar</option>
<option value="Goreswar">Goreswar</option>
<option value="Gurmow Balahati">Gurmow Balahati</option>
<option value="Kaurbaha">Kaurbaha</option>
<option value="Khandikar">Khandikar</option>
<option value="Maharipara">Maharipara</option>
<option value="Naokata">Naokata</option>
<option value="Niz-Betna">Niz-Betna</option>
<option value="Oubari">Oubari</option>
<option value="Rampur">Rampur</option>
<option value="Suagpur">Suagpur</option>
<option value="Tengajhar">Tengajhar</option>
<option value="Borphena">Borphena</option>
<option value="Dangari Gaon">Dangari Gaon</option>
<option value="Gadhuligaon">Gadhuligaon</option>
<option value="Ghoramara Rupahi">Ghoramara Rupahi</option>
<option value="Gola Gaon">Gola Gaon</option>
<option value="Jalah">Jalah</option>
<option value="Jalah Gaon">Jalah Gaon</option>
<option value="Kaklabari">Kaklabari</option>
<option value="Kamardwisa">Kamardwisa</option>
<option value="Rabanguri">Rabanguri</option>
<option value="Ramchartari">Ramchartari</option>
<option value="Rupahi">Rupahi</option>
<option value="Rupaphuli">Rupaphuli</option>
<option value="Salbari">Salbari</option>
<option value="Silbari">Silbari</option>
<option value="Gandhibari">Gandhibari</option>
<option value="Kaurbaha">Kaurbaha</option>
<option value="Khatarbari">Khatarbari</option>
<option value="Mazagari">Mazagari</option>
<option value="Nagrijuli">Nagrijuli</option>
<option value="Nizdefeli">Nizdefeli</option>
<option value="No 1 Pachim Defali">No 1 Pachim Defali</option>
<option value="No 1 Pub-Kumarikata">No 1 Pub-Kumarikata</option>
<option value="No 2 Pub-Kumarikata">No 2 Pub-Kumarikata</option>
<option value="No 3 Pachim Defali">No 3 Pachim Defali</option>
<option value="No 3 Pub-Kumarikata">No 3 Pub-Kumarikata</option>
<option value="Panbari">Panbari</option>
<option value="Duwarkuchi">Duwarkuchi</option>
<option value="No 1 Dakhin Kumarikata">No 1 Dakhin Kumarikata</option>
<option value="No 1 Pachim Kumarikata">No 1 Pachim Kumarikata</option>
<option value="No 1 Tamulpur">No 1 Tamulpur</option>
<option value="No 2 Dakhin Kumarikata">No 2 Dakhin Kumarikata</option>
<option value="No 2 Pachim Kumarikata">No 2 Pachim Kumarikata</option>
<option value="No 2 Tamulpur">No 2 Tamulpur</option>
<option value="No 3 Dakhin Kumarikata">No 3 Dakhin Kumarikata</option>
<option value="No 3 Pachim Kumarikata">No 3 Pachim Kumarikata</option>
<option value="No 3 Tamulpur">No 3 Tamulpur</option>
<option value="No 4 Dakhin Kumarikata">No 4 Dakhin Kumarikata</option>
<option value="No 4 Pachim Kumarikata">No 4 Pachim Kumarikata</option>
<option value="No 4 Tamulpur">No 4 Tamulpur</option>
<option value="No 5 Tamulpur">No 5 Tamulpur</option>
<option value="Dalakati Borobazar">Dalakati Borobazar</option>
<option value="Gerua">Gerua</option>
<option value="Attareekhat">Attareekhat</option>
<option value="Bamunjuli">Bamunjuli</option>
<option value="Bhergami">Bhergami</option>
<option value="Bholatar">Bholatar</option>
<option value="Budura">Budura</option>
<option value="Dimakuchi">Dimakuchi</option>
<option value="Garuajhar">Garuajhar</option>
<option value="Gopachachuba">Gopachachuba</option>
<option value="Goybari">Goybari</option>
<option value="Hahchara">Hahchara</option>
<option value="Jabangapathar">Jabangapathar</option>
<option value="Kalikhola">Kalikhola</option>
<option value="Khagrabari">Khagrabari</option>
<option value="Khasiachuba">Khasiachuba</option>
<option value="Mwilapara">Mwilapara</option>
<option value="Nagachuba">Nagachuba</option>
<option value="No. 1 Sonajuli">No. 1 Sonajuli</option>
<option value="Nonaikhuti">Nonaikhuti</option>
<option value="Orengajuli">Orengajuli</option>
<option value="Panesheli">Panesheli</option>
<option value="Paschim Patla">Paschim Patla</option>
<option value="Rajagarh">Rajagarh</option>
<option value="Rupakhat">Rupakhat</option>
<option value="Suklai">Suklai</option>
<option value="Tenkibasti">Tenkibasti</option>
<option value="Totolapara">Totolapara</option>
<option value="Kacharison">Kacharison</option>
<option value="Natunpanbari">Natunpanbari</option>
<option value="Koupati">Koupati</option>
<option value="Balipara">Balipara</option>
<option value="Bhakatpara">Bhakatpara</option>
<option value="Bhuyankhat">Bhuyankhat</option>
<option value="Chengapathar">Chengapathar</option>
<option value="Dumuruguri">Dumuruguri</option>
<option value="Gerua">Gerua</option>
<option value="Jhargaon Kadamguri">Jhargaon Kadamguri</option>
<option value="Kacharitol">Kacharitol</option>
<option value="Kalaigaon Town">Kalaigaon Town</option>
<option value="Majorchuba">Majorchuba</option>
<option value="Naptipara">Naptipara</option>
<option value="Niz-Kalaigaon">Niz-Kalaigaon</option>
<option value="Ranipukhuri">Ranipukhuri</option>
<option value="Tepakhat">Tepakhat</option>
<option value="Jhargaon">Jhargaon</option>
<option value="Khoirabari">Khoirabari</option>
<option value="Kuhiarkuchi">Kuhiarkuchi</option>
<option value="Mahaliapara">Mahaliapara</option>
<option value="Niz-Chinakona">Niz-Chinakona</option>
<option value="64 Dhansiri">64 Dhansiri</option>
<option value="66 Dhansiri">66 Dhansiri</option>
<option value="Alabari">Alabari</option>
<option value="Bahipukhuri">Bahipukhuri</option>
<option value="Gelabil">Gelabil</option>
<option value="Habigaon">Habigaon</option>
<option value="Jagyapur">Jagyapur</option>
<option value="Lamabari">Lamabari</option>
<option value="Mazbat">Mazbat</option>
<option value="Merabil">Merabil</option>
<option value="Naoherua">Naoherua</option>
<option value="Orang">Orang</option>
<option value="Phulaguri">Phulaguri</option>
<option value="Rangapani">Rangapani</option>
<option value="Rowtagaon">Rowtagaon</option>
<option value="Saikia chuburi">Saikia chuburi</option>
<option value="Mudoibari">Mudoibari</option>
<option value="Bhakatpara">Bhakatpara</option>
<option value="Mudoibari">Mudoibari</option>
<option value="Barigaon">Barigaon</option>
<option value="Barnagaon">Barnagaon</option>
<option value="Dhansiri">Dhansiri</option>
<option value="Ekrabari">Ekrabari</option>
<option value="Kajiamati">Kajiamati</option>
<option value="Mohanpur">Mohanpur</option>
<option value="Phuhurabari">Phuhurabari</option>
<option value="Purani Garaibari">Purani Garaibari</option>
<option value="Purani Hapagaon">Purani Hapagaon</option>
<option value="Rowta">Rowta</option>
<option value="Rowta Bagan">Rowta Bagan</option>
<option value="Rowta Station">Rowta Station</option>
<option value="Sivapur">Sivapur</option>
<option value="Alabari">Alabari</option>
<option value="Ambagaon">Ambagaon</option>
<option value="Amjuli">Amjuli</option>
<option value="Bangaon">Bangaon</option>
<option value="Barnagaon">Barnagaon</option>
<option value="Bengbari">Bengbari</option>
<option value="Bhairaguri">Bhairaguri</option>
<option value="Bhutiachang">Bhutiachang</option>
<option value="Borigaon">Borigaon</option>
<option value="Borla">Borla</option>
<option value="Chumuapara">Chumuapara</option>
<option value="Ghagra">Ghagra</option>
<option value="Harisinga">Harisinga</option>
<option value="Hatigarh">Hatigarh</option>
<option value="Jaberitola">Jaberitola</option>
<option value="Khairajangal">Khairajangal</option>
<option value="Khamabari">Khamabari</option>
<option value="Khowrang">Khowrang</option>
<option value="Merbangchuba">Merbangchuba</option>
<option value="Murmela">Murmela</option>
<option value="Odala">Odala</option>
<option value="Panery">Panery</option>
<option value="Purandia">Purandia</option>
<option value="Ratanpur">Ratanpur</option>
<option value="Santipur">Santipur</option>
<option value="Sapangaon">Sapangaon</option>
<option value="Sapkhaiti">Sapkhaiti</option>
<option value="Sastrapara">Sastrapara</option>
<option value="Simluguri">Simluguri</option>
<option value="Sonaigaon">Sonaigaon</option>
<option value="Tamulbari">Tamulbari</option>
<option value="Udalguri">Udalguri</option>
<option value="Borobazar">Borobazar</option>
<option value="Rowmari">Rowmari</option>
<option value="Panbari">Panbari</option>
<option value="Bhagpuri">Bhagpuri</option>
<option value="Borla">Borla</option>
<option value="Simla">Simla</option>